---
- hosts: 34.224.223.103
  sudo: true
  vars:
   packages: ['vim', 'git', 'curl']
  tasks:
- name: Install Package
  apt: name={{ item }} state=latest
  with_items: packages
- name: Install httpd Package
  yum: name=httpd state=latest
- name: Copy httpd configuration file
  copy: src=/data/httpd.original dest=/etc/httpd/conf/httpd.conf
- name: Start and Enable httpd service
  service: name=httpd state=restarted enabled=yes
...
